## ============================================================================================= ##
#  modules/manifests/core/renovate/configmap.tf                                                   #
#                                                                                                 #
#  Renovate global configuration (config.js).                                                     #
#  Per-repository renovate.json files are still honored and override global defaults.             #
## ============================================================================================= ##
locals {
  config_js = <<-EOT
    // Generated by Terraform: modules/manifests/core/renovate/configmap.tf
    // Global Renovate configuration. Repository-level renovate.json files take precedence.
    module.exports = {
      platform: 'github',
      autodiscover: ${var.config.autodiscover},
      requireConfig: '${var.config.require_config}',
      onboarding: ${var.config.onboarding},
      onboardingConfig: {
        extends: ['config:recommended'],
      },
    %{if var.config.autodiscover_filter != null}  autodiscoverFilter: '${var.config.autodiscover_filter}',
    %{endif}%{if length(var.config.repositories) > 0}  repositories: [${join(", ", formatlist("'%s'", var.config.repositories))}],
    %{endif}${var.config.config_js_extra != null ? var.config.config_js_extra : ""}
    };
  EOT
}

resource "kubernetes_config_map_v1" "configmap" {
  count = var.enabled ? 1 : 0
  metadata {
    name      = "${var.config.name}-config"
    namespace = kubernetes_namespace_v1.this[0].metadata[0].name
  }
  data = {
    "config.js" = local.config_js
  }
  depends_on = [kubernetes_namespace_v1.this]
}
